apiVersion: v1
kind: ConfigMap
metadata:
  name: env-be
data:
  FLASK_RUN_HOST: "0.0.0.0"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: image-BE-name:latest
          imagePullPolicy: Always
          envFrom:
            - configNapRef:
                name: env-be
          ports:
            - containerPort: 5000